from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class VCDSignal:
    name: str
    code: str
    width: int = 1
    changes: list[tuple[int, str]] = field(default_factory=list)


@dataclass
class VCDData:
    timescale: str = "1ns"
    end_time: int = 0
    signals: list[VCDSignal] = field(default_factory=list)

    def signal(self, name: str) -> VCDSignal | None:
        return next((signal for signal in self.signals if signal.name == name), None)


def parse_vcd(path: Path) -> VCDData:
    data = VCDData()
    scopes: list[str] = []
    # VCD permits several hierarchical signal names to share one identifier
    # code (for example an interface net and the DUT port connected to it).
    # Keep every alias so each name renders the same value changes.
    by_code: dict[str, list[VCDSignal]] = {}
    current_time = 0
    in_timescale = False
    timescale_parts: list[str] = []

    with path.open("r", encoding="utf-8", errors="replace") as stream:
        for raw_line in stream:
            line = raw_line.strip()
            if not line:
                continue
            if in_timescale:
                if "$end" in line:
                    before = line.split("$end", 1)[0].strip()
                    if before:
                        timescale_parts.append(before)
                    data.timescale = " ".join(timescale_parts).replace(" ", "") or "1ns"
                    in_timescale = False
                else:
                    timescale_parts.append(line)
                continue
            if line.startswith("$timescale"):
                rest = line[len("$timescale") :].strip()
                if "$end" in rest:
                    data.timescale = rest.split("$end", 1)[0].strip().replace(" ", "") or "1ns"
                else:
                    in_timescale = True
                    if rest:
                        timescale_parts.append(rest)
                continue
            if line.startswith("$scope"):
                parts = line.split()
                if len(parts) >= 3:
                    scopes.append(parts[2])
                continue
            if line.startswith("$upscope"):
                if scopes:
                    scopes.pop()
                continue
            if line.startswith("$var"):
                parts = line.split()
                if len(parts) >= 6:
                    width = int(parts[2])
                    code = parts[3]
                    reference = parts[4]
                    full_name = ".".join([*scopes, reference])
                    signal = VCDSignal(full_name, code, width)
                    data.signals.append(signal)
                    by_code.setdefault(code, []).append(signal)
                continue
            if line.startswith("#"):
                try:
                    current_time = int(line[1:])
                    data.end_time = max(data.end_time, current_time)
                except ValueError:
                    pass
                continue
            if line[0] in "01xXzZ":
                for signal in by_code.get(line[1:], []):
                    signal.changes.append((current_time, line[0].lower()))
                continue
            if line[0] in "bBrR":
                parts = line.split()
                if len(parts) == 2:
                    for signal in by_code.get(parts[1], []):
                        signal.changes.append((current_time, parts[0][1:].lower()))

    return data


def value_at(signal: VCDSignal, time: int) -> str:
    value = "x"
    for change_time, change_value in signal.changes:
        if change_time > time:
            break
        value = change_value
    return value


def write_demo_vcd(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "$date", "  Generated by SV Studio Demo Engine", "$end",
        "$version", "  SV Studio 0.1", "$end",
        "$timescale 1ns $end",
        "$scope module tb_top $end",
        "$var wire 1 ! clk $end",
        "$var wire 1 \" rst_n $end",
        "$var wire 1 # enable $end",
        "$var wire 4 $ count $end",
        "$upscope $end", "$enddefinitions $end", "$dumpvars",
        "0!", "0\"", "0#", "b0000 $", "$end",
    ]
    count = 0
    for time in range(5, 126, 5):
        lines.append(f"#{time}")
        lines.append(("1" if (time // 5) % 2 else "0") + "!")
        if time == 15:
            lines.append("1\"")
        if time == 25:
            lines.append("1#")
        if 30 <= time < 100 and time % 10 == 0:
            count = (count + 1) & 0xF
            lines.append(f"b{count:04b} $")
        if time == 95:
            lines.append("0#")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
